from PyQt5 import QtCore, QtGui, QtWidgets
from . import res_money_rc
class MoneyUI(QtWidgets.QWidget):
    def __init__(self,parent):
        super().__init__(parent)
        Money = QtWidgets.QWidget(self)
        Money.setObjectName("Money")
        Money.setStyleSheet("background-color: #fcfcfc")
        Money.resize(1920, 850)
        self.widget = QtWidgets.QWidget(Money)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1920, 60))
        self.widget.setStyleSheet("border: 2px solid #24292E;")
        self.widget.setObjectName("widget")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(485, 0, 1070, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("padding-left: 15px;\n"
"border: 2px solid #24292E;")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(62, 0, 221, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(36, 41, 46);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(36, 41, 46);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/backLight.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(285, 0, 60, 60))
        self.pushButton_2.setStyleSheet("background-color: rgb(36, 41, 46);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/money-bag.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(1860, 0, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Caviar Dreams")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(36, 41, 46);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(1798, 0, 60, 60))
        self.pushButton_4.setStyleSheet("background-color: rgb(36, 41, 46);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/minimize Light.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(1554, 0, 60, 60))
        self.pushButton_5.setStyleSheet("background-color: rgb(36, 41, 46);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_5.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/InVoiceL.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(1616, 0, 180, 60))
        font = QtGui.QFont()
        font.setFamily("Caviar Dreams")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(36, 41, 46);\n"
"color: rgb(255, 255, 255);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/wallet-filled-money-tool.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon4)
        self.pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_6.setCheckable(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(347, 0, 140, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(36, 41, 46);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.widget_2 = QtWidgets.QWidget(Money)
        self.widget_2.setGeometry(QtCore.QRect(1615, 65, 185, 154))
        self.widget_2.setStyleSheet("border: 2px solid #24292E;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(252, 252, 252);")
        self.widget_2.setObjectName("widget_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 0, 185, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(36, 41, 46);\n"
"color: rgb(255, 255, 255);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/inc_White.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon5)
        self.pushButton_7.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 52, 185, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("\n"
"color:  rgb(36, 41, 46);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons8-reserve-filled-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon6)
        self.pushButton_8.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 104, 185, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("color:  rgb(36, 41, 46);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons8-cashbook-filled-100 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon7)
        self.pushButton_9.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.IncomeWid = QtWidgets.QWidget(Money)
        self.IncomeWid.setGeometry(QtCore.QRect(0, 70, 1920, 780))
        self.IncomeWid.setStyleSheet("#IncomeWid{\n"
"border: 2px solid #24292E;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(252, 252, 252);\n"
"}")
        self.IncomeWid.setObjectName("IncomeWid")
        self.label_2 = QtWidgets.QLabel(self.IncomeWid)
        self.label_2.setGeometry(QtCore.QRect(70, 20, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.IncomeWid)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 40, 40))
        self.label_3.setStyleSheet("image: url(:/icons/inc_Dark.svg);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.IncomeWid.raise_()
        self.widget.raise_()
        self.widget_2.raise_()

        self.retranslateUi(Money)
        QtCore.QMetaObject.connectSlotsByName(Money)

    def retranslateUi(self, Money):
        _translate = QtCore.QCoreApplication.translate
        Money.setWindowTitle(_translate("Money", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Money", "OPERATIONS ON MONEY"))
        self.label.setText(_translate("Money", "MONEY"))
        self.pushButton_3.setText(_translate("Money", "X"))
        self.pushButton_6.setText(_translate("Money", "WALLET"))
        self.pushButton_6.setShortcut(_translate("Money", "Ctrl+W"))
        self.label_4.setText(_translate("Money", "0,00,000"))
        self.pushButton_7.setText(_translate("Money", "INCOME"))
        self.pushButton_8.setText(_translate("Money", "EXPENSE"))
        self.pushButton_9.setText(_translate("Money", "SUMMARY"))
        self.label_2.setText(_translate("Money", "INCOME"))

